#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Apr 12, 2023 12:20:13 AM CEST  platform: Linux

import tkinter as tk
from tkinter.constants import *

import releaser_GUI as releaser

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top44, _w44
    _top44 = root
    _w44 = releaser.main(_top44)
    root.mainloop()

if __name__ == '__main__':
    releaser.start_up()




